export const ICONS_CONFIG = [
  { animalId: "lion", label: "Lion" },
  { animalId: "wolf", label: "Wolf" },
  { animalId: "giraffe", label: "Giraffe" },
  { animalId: "bear", label: "Bear" },
  { animalId: "chicken", label: "Chicken" },
  { animalId: "cat", label: "Cat" },
  { animalId: "tiger", label: "Tiger" },
  { animalId: "elephant", label: "Elephant" },
  { animalId: "frog", label: "Frog" },
  { animalId: "fox", label: "Fox" },
  { animalId: "penguin", label: "Penguin" },
  { animalId: "butterfly", label: "Butterfly" },
  { animalId: "dolphin", label: "Dolphin" },
  { animalId: "unicorn", label: "Unicorn" },
  { animalId: "octopus", label: "Octopus" },
  { animalId: "zebra", label: "Zebra" },
  { animalId: "duck", label: "Duck" },
  { animalId: "donkey", label: "Donkey" },
  { animalId: "horse", label: "Horse" },
  { animalId: "fish", label: "Fish" },
  { animalId: "monkey", label: "Monkey" },
  { animalId: "whale", label: "Whale" },
  { animalId: "dog", label: "Dog" },
  { animalId: "bird", label: "Bird" },
  { animalId: "owl", label: "Owl" },
]

export const DIFFICULTY_CONFIG = {
  easy: {
    timeBonus: 30,
    label: "Easy",
    pairs: [3, 4, 5, 6, 7, 8],
    shuffleCards: false,
    scoreMultiplier: 1,
  },
  medium: {
    timeBonus: 20,
    label: "Medium",
    pairs: [9, 10, 12, 15],
    shuffleCards: false,
    scoreMultiplier: 2,
  },
  hard: {
    timeBonus: 10,
    label: "Hard",
    pairs: [15, 16, 18],
    shuffleCards: true,
    scoreMultiplier: 3,
  },
}
