export const ANIMALS_CONFIG = [
  { itemId: "lion", label: "Lion" },
  { itemId: "wolf", label: "Wolf" },
  { itemId: "giraffe", label: "Giraffe" },
  { itemId: "bear", label: "Bear" },
  { itemId: "chicken", label: "Chicken" },
  { itemId: "cat", label: "Cat" },
  { itemId: "tiger", label: "Tiger" },
  { itemId: "elephant", label: "Elephant" },
  { itemId: "frog", label: "Frog" },
  { itemId: "fox", label: "Fox" },
  { itemId: "penguin", label: "Penguin" },
  { itemId: "butterfly", label: "Butterfly" },
  { itemId: "dolphin", label: "Dolphin" },
  { itemId: "unicorn", label: "Unicorn" },
  { itemId: "octopus", label: "Octopus" },
  { itemId: "zebra", label: "Zebra" },
  { itemId: "duck", label: "Duck" },
  { itemId: "donkey", label: "Donkey" },
  { itemId: "horse", label: "Horse" },
  { itemId: "fish", label: "Fish" },
  { itemId: "monkey", label: "Monkey" },
  { itemId: "whale", label: "Whale" },
  { itemId: "dog", label: "Dog" },
  { itemId: "bird", label: "Bird" },
  { itemId: "owl", label: "Owl" },
]

export const FLAGS_CONFIG = [
  { itemId: "israel", label: "Israel" },
  { itemId: "germany", label: "Germany" },
  { itemId: "usa", label: "USA" },
  { itemId: "uk", label: "UK" },
  { itemId: "france", label: "France" },
  { itemId: "italy", label: "Italy" },
  { itemId: "spain", label: "Spain" },
  { itemId: "japan", label: "Japan" },
  { itemId: "china", label: "China" },
  { itemId: "brazil", label: "Brazil" },
  { itemId: "canada", label: "Canada" },
  { itemId: "australia", label: "Australia" },
  { itemId: "india", label: "India" },
  { itemId: "russia", label: "Russia" },
  { itemId: "mexico", label: "Mexico" },
  { itemId: "southkorea", label: "S. Korea" },
  { itemId: "argentina", label: "Argentina" },
  { itemId: "turkey", label: "Turkey" },
  { itemId: "netherlands", label: "Netherlands" },
  { itemId: "sweden", label: "Sweden" },
  { itemId: "norway", label: "Norway" },
  { itemId: "switzerland", label: "Switzerland" },
  { itemId: "poland", label: "Poland" },
  { itemId: "portugal", label: "Portugal" },
  { itemId: "greece", label: "Greece" },
  { itemId: "ukraine", label: "Ukraine" },
  { itemId: "egypt", label: "Egypt" },
  { itemId: "southafrica", label: "S. Africa" },
  { itemId: "nigeria", label: "Nigeria" },
  { itemId: "saudiarabia", label: "Saudi Arabia" },
  { itemId: "uae", label: "UAE" },
  { itemId: "indonesia", label: "Indonesia" },
  { itemId: "thailand", label: "Thailand" },
  { itemId: "pakistan", label: "Pakistan" },
  { itemId: "bangladesh", label: "Bangladesh" },
  { itemId: "vietnam", label: "Vietnam" },
  { itemId: "iran", label: "Iran" },
  { itemId: "iraq", label: "Iraq" },
  { itemId: "jordan", label: "Jordan" },
  { itemId: "morocco", label: "Morocco" },
  { itemId: "kenya", label: "Kenya" },
  { itemId: "ethiopia", label: "Ethiopia" },
  { itemId: "ghana", label: "Ghana" },
  { itemId: "newzealand", label: "New Zealand" },
  { itemId: "singapore", label: "Singapore" },
  { itemId: "malaysia", label: "Malaysia" },
  { itemId: "philippines", label: "Philippines" },
  { itemId: "chile", label: "Chile" },
  { itemId: "colombia", label: "Colombia" },
  { itemId: "peru", label: "Peru" },
  { itemId: "venezuela", label: "Venezuela" },
  { itemId: "cuba", label: "Cuba" },
  { itemId: "finland", label: "Finland" },
  { itemId: "denmark", label: "Denmark" },
  { itemId: "austria", label: "Austria" },
  { itemId: "belgium", label: "Belgium" },
  { itemId: "romania", label: "Romania" },
  { itemId: "hungary", label: "Hungary" },
  { itemId: "czech", label: "Czech Rep." },
  { itemId: "slovakia", label: "Slovakia" },
]

export const CARS_CONFIG = [
  { itemId: "bmw", label: "BMW" },
  { itemId: "mercedes", label: "Mercedes" },
  { itemId: "ferrari", label: "Ferrari" },
  { itemId: "audi", label: "Audi" },
  { itemId: "toyota", label: "Toyota" },
  { itemId: "volkswagen", label: "VW" },
  { itemId: "porsche", label: "Porsche" },
  { itemId: "lamborghini", label: "Lambo" },
  { itemId: "ford", label: "Ford" },
  { itemId: "chevrolet", label: "Chevrolet" },
  { itemId: "honda", label: "Honda" },
  { itemId: "nissan", label: "Nissan" },
  { itemId: "hyundai", label: "Hyundai" },
  { itemId: "kia", label: "Kia" },
  { itemId: "mazda", label: "Mazda" },
  { itemId: "subaru", label: "Subaru" },
  { itemId: "rollsroyce", label: "Rolls-Royce" },
  { itemId: "bentley", label: "Bentley" },
  { itemId: "maserati", label: "Maserati" },
  { itemId: "jaguar", label: "Jaguar" },
  { itemId: "volvo", label: "Volvo" },
  { itemId: "peugeot", label: "Peugeot" },
  { itemId: "renault", label: "Renault" },
  { itemId: "tesla", label: "Tesla" },
  { itemId: "bugatti", label: "Bugatti" },
]

export const FOOD_CONFIG = [
  { itemId: "pizza", label: "Pizza" },
  { itemId: "sushi", label: "Sushi" },
  { itemId: "burger", label: "Burger" },
  { itemId: "taco", label: "Taco" },
  { itemId: "ramen", label: "Ramen" },
  { itemId: "icecream", label: "Ice Cream" },
  { itemId: "cake", label: "Cake" },
  { itemId: "donut", label: "Donut" },
  { itemId: "hotdog", label: "Hot Dog" },
  { itemId: "croissant", label: "Croissant" },
  { itemId: "dumpling", label: "Dumpling" },
  { itemId: "fries", label: "Fries" },
  { itemId: "waffle", label: "Waffle" },
  { itemId: "cupcake", label: "Cupcake" },
  { itemId: "pretzel", label: "Pretzel" },
  { itemId: "cookie", label: "Cookie" },
  { itemId: "lollipop", label: "Lollipop" },
  { itemId: "popcorn", label: "Popcorn" },
  { itemId: "strawberry", label: "Strawberry" },
  { itemId: "watermelon", label: "Watermelon" },
  { itemId: "avocado", label: "Avocado" },
  { itemId: "mushroom", label: "Mushroom" },
  { itemId: "broccoli", label: "Broccoli" },
  { itemId: "cheese", label: "Cheese" },
  { itemId: "bacon", label: "Bacon" },
]

// Keep backward compat alias
export const ICONS_CONFIG = ANIMALS_CONFIG

export const CAMPAIGN_LEVELS = [
  { level: 1,  pairs: 3,  difficulty: "easy"   as const, category: "animals" as const, label: "Animal Starter" },
  { level: 2,  pairs: 4,  difficulty: "easy"   as const, category: "food"    as const, label: "Tasty Bites" },
  { level: 3,  pairs: 5,  difficulty: "easy"   as const, category: "flags"   as const, label: "World Tour I" },
  { level: 4,  pairs: 6,  difficulty: "easy"   as const, category: "cars"    as const, label: "Fast Lanes" },
  { level: 5,  pairs: 6,  difficulty: "medium" as const, category: "animals" as const, label: "Wild Kingdom" },
  { level: 6,  pairs: 8,  difficulty: "medium" as const, category: "food"    as const, label: "Food Frenzy" },
  { level: 7,  pairs: 9,  difficulty: "medium" as const, category: "flags"   as const, label: "World Tour II" },
  { level: 8,  pairs: 10, difficulty: "medium" as const, category: "cars"    as const, label: "Speed Garage" },
  { level: 9,  pairs: 12, difficulty: "hard"   as const, category: "animals" as const, label: "Safari Master" },
  { level: 10, pairs: 15, difficulty: "hard"   as const, category: "flags"   as const, label: "Grand Champion" },
]

export const CARD_THEME_CONFIG = {
  classic: { back: "#6D28D9", border: "rgba(255,255,255,0.3)", question: "rgba(255,255,255,0.9)", label: "Classic" },
  dark:    { back: "#111827", border: "rgba(255,255,255,0.15)", question: "rgba(255,255,255,0.7)", label: "Dark" },
  neon:    { back: "#0F172A", border: "#22D3EE", question: "#22D3EE", label: "Neon" },
  minimal: { back: "rgba(255,255,255,0.1)", border: "rgba(255,255,255,0.4)", question: "rgba(255,255,255,0.8)", label: "Minimal" },
}

export const DIFFICULTY_CONFIG = {
  easy: {
    timeBonus: 30,
    label: "Easy",
    pairs: [3, 4, 5, 6, 7, 8],
    shuffleCards: false,
    scoreMultiplier: 1,
  },
  medium: {
    timeBonus: 20,
    label: "Medium",
    pairs: [9, 10, 12, 15],
    shuffleCards: false,
    scoreMultiplier: 2,
  },
  hard: {
    timeBonus: 10,
    label: "Hard",
    pairs: [16, 18],
    shuffleCards: true,
    scoreMultiplier: 3,
  },
}
